Develop/10
SOLUX-APP1-FLORY/Flory-Android pull request #11
Opened 2024-06-24 12:24 UTC by sehee0207

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #10

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 이웃 검색 페이지 구현
- fragment_gift 페이지 구현
- 선물하기 중에서 이웃 선택 페이지까지만 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/0d2858cd-949c-4c0b-ac1a-350ed97197b2)
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/9000e8fa-dbbd-4e97-a8d3-627dc70d67e1)
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/77204fcb-0de9-4de0-847b-53ff82756a05)

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
피드백 부탁드립니다! (id 같은 거 잘 한건지 모르겠어요 ...)
이번 주에 더 열심히 해오겠습니다 🫡

2024-06-24 12:49 UTC, gaeulzzang requested changes
리사이클러뷰 잘 사용하셨네요~ id 네이밍 수정해주시고, 아이콘 svg로 임포트해서 사용해주시고 bias 사용한거 바꿔주시면 될 것 같아요!! 너무 어려우면 제게 바로바로 말씀해주세요 😄

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/drawable/ic_gift_addcircle.png
아이콘들은 svg로 import해야 깨지지 않습니답. 피그마에서 svg로 다운로드 받으시고 vector image asset으로 넣어주세용

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectneighbor.xml
> +                tools:layout_editor_absoluteY="90dp" />
수치로 절대적 위치를 주는건 좋지 않습니다 image view와의 margin 값으로 text view 위치를 설정해주는 코드로 수정해주세욥

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectneighbor.xml
> +            app:layout_constraintVertical_bias="0.507">
bias를 쓰신 이유가 먼가요?

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_searchneighbor.xml
> +            android:layout_height="350dp"
리사이클러뷰 너비와 높이를 직접 숫자로 정해주는건 화면 호환성에 좋지 않습니답 #
```suggestion
        <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/rv_searchneighbors"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
```
이렇게 해주시고 recyclerview를 감싸는 layout을 만들어서 paddingHorizontal을 주시면 코드가 깔끔해집니다

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectneighbor.xml
> +                tools:layout_editor_absoluteY="115dp" />
얘도 수정!!

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectneighbor.xml
> +        android:id="@+id/textView4"
```suggestion
        android:id="@+id/tv_my_neighbors"
```
아이디 컨벤션 지키기!!

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/item_gift_selectneighbors.xml
> +        android:id="@+id/tv_gift_user"
```suggestion
        android:id="@+id/iv_gift_user"
```

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/item_gift_searchneighbors.xml
> +        android:id="@+id/tv_gift_user"
```suggestion
        android:id="@+id/iv_gift_user"
```

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_gift.xml
> +            app:layout_constraintVertical_bias="0.184" />
bias 사용하지 마시고 상위 레이아웃에 padding 줘서 위치 설정해주세요

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_gift.xml
> +            app:layout_constraintTop_toTopOf="@+id/iv_gift_flowerconfirm" />
```suggestion
            app:layout_constraintTop_toTopOf="@id/iv_gift_flowerconfirm" />
```
@+id는 id 새로 만들어줄 때 사용, @id는 id를 이용할 때 사용

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_gift.xml
> +            app:layout_constraintStart_toStartOf="@+id/iv_gift_flowerconfirm" />
밑에도 @id로 모두 수정해주세용

2024-06-24 12:49 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_gift.xml
> +            android:id="@+id/iv_gift_flowersendtext"
```suggestion
            android:id="@+id/tv_gift_flowersendtext"
```

2024-06-28 15:44 UTC, sehee0207 commented on app/src/main/res/layout/fragment_gift.xml
> +            android:id="@+id/iv_gift_flowersendtext"
헉 달아주신 것들 이제 확인했네요 ...!!! 감사합니다..

2024-06-30 12:50 UTC, sehee0207 commented
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/c591663f-8594-4bde-a0dc-2c274ec0e173)
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/9e7801ca-9b18-4416-829e-8e7b249ad705)
![image](https://github.com/SOLUX-APP1-FLORY/Flory-Frontend/assets/65457903/a315ffea-6d8a-4015-a77e-2b088de5baa5)

수정 완료했습니다!

2024-06-30 13:47 UTC, gaeulzzang approved these changes
코드가 깔쌈하고 쌈@뽕하네요 >< 수고하셨습니다 세희님 ❤️

2024-06-30 14:35 UTC, merged