feat: 이웃 목록 && 팔로우 취소 화면 UI 구현
SOLUX-APP1-FLORY/Flory-Android pull request #24
Opened 2024-07-13 10:34 UTC by sehee0207

## 📌𝘐𝘴𝘴𝘶𝘦𝘴
- closed #21 

## 📎𝘞𝘰𝘳𝘬 𝘋𝘦𝘴𝘤𝘳𝘪𝘱𝘵𝘪𝘰𝘯
- 이웃 목록 화면 UI 구현
- 팔로우 취소 다이얼로그 구현
- 선물하기 페이지 2 이웃 목록 리사이클러뷰 뜨도록 구현
- 선물하기 페이지 3 선택한 이웃 넘어가도록 구현

## 📷𝘚𝘤𝘳𝘦𝘦𝘯𝘴𝘩𝘰𝘵
https://github.com/user-attachments/assets/f16d4118-d60c-4207-bdbe-8f048660da81

## 💬𝘛𝘰 𝘙𝘦𝘷𝘪𝘦𝘸𝘦𝘳𝘴
하다보니까 이것저것 하고 싶어서 많이 해버렷습니다..
이번주에도 많이 도와주신 가을님께 감사를 드려요
![MuaKissGIF](https://github.com/user-attachments/assets/ce834a34-4e37-4b9c-8f1e-8dfe435e4810)

2024-07-13 17:30 UTC, younheejae approved these changes
오..나날이 발전하시네여
이제 웬만한거 다 짤 수 있을것같은데용
수고하셨습니다~!!

2024-07-15 15:51 UTC, gaeulzzang requested changes
로직은 with(binding), 스코프 함수 적용하면 코드가 깔끔해질 것 같습니다
xml은 피그마랑 padding, margin 차이가 많이 나서 수정해야될 것 같네요!! linear layout 보다는 constraint layout 사용해주시면 좋을 것 같아요!! width는 0dp, wrap_content, match_parent만 사용합시다!! 그리고 각 뷰마다 marginStart, marginEnd 주는 것보다는 상위 레이아웃에서 paddingHorizontal을 주는게 훨씬 간편합니다..!! 전체적으로 UI 가로 여백이 많은 것 같네요!! 이 부분 수정해서 리팩 진행해주시면 될 것 같아요
수고 많으셨습니다~!!^^

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +            android:layout_height="52dp"
```suggestion
            android:layout_width="52dp"
            android:layout_height="0dp"
            app:layout_constraintDimensionRatio="1"
```
이렇게 가로 세로 1대 1 비율로 조정해줄 수 있습니다

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +        android:layout_marginTop="40dp"
36dp로 수정해주세요!!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +            android:layout_marginTop="10dp"
8dp로 수정!! 피그마대로 margin값 주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +        android:layout_marginTop="40dp"
28dp로 수정

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +        android:id="@+id/btn_no"
```suggestion
        android:id="@+id/btn_follow_cancel_no"
```
이런 식으로 네이밍 수정해주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +        android:id="@+id/btn_yes"
```suggestion
        android:id="@+id/btn_follow_cancel_yes"
```
네이밍 수정해주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
fragment_follow_cancel_dialog로 파일 네이밍 수정하기!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_profile_neighborlist.xml
> +    android:layout_height="33dp"
```suggestion
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
```
이런식으로 주고 recyclerview 에 paddingHorizontal="20dp"로 주기!!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_profile_neighborlist.xml
> +        android:layout_marginStart="16dp"
marginStart 없애기

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_profile_neighborlist.xml
> +        android:text="선재"
tools:text로 preview에서만 text 보여줄 수 있어요
```suggestion
        tools:text="선재"
```

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_profile_neighborlist.xml
> +    </androidx.constraintlayout.widget.ConstraintLayout>
이렇게 주기 말고 팔로우 취소라는 버튼을 만들기!!
버튼 width, height 모두 wrap_content로 만들고 paddingHorizontal="16dp", paddingVertical="5dp"로 주기!

2024-07-15 15:51 UTC, gaeulzzang commented on gradle/libs.versions.toml
> +agp = "8.4.0"
8.4.0으로 바꾼 이유가 뭔가요??

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_gift_selectneighbors.xml
> +    android:layout_marginTop="14dp"
얘또 width는 match_parent, height는 wrap_content로 주기
marginTop은 왜 14dp로 주셨나요?

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/item_gift_selectneighbors.xml
> +        app:layout_constraintStart_toEndOf="@+id/iv_selectneighbor_image"
이거 없애고 endend, botbot, toptop만 주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_neighbors.xml
> +                android:id="@+id/rv_neighborslist"
rv_neighbors가 맞습니다
복수형을 쓸 수 있다면 뒤에 list를 붙이지 않습니다

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_neighbors.xml
> +                tools:listitem="@layout/item_profile_neighborlist" />
neighborslist랑 neighborlist 중에 원만한 합의 하시길 바랍니다 ㅋㅋㅋㅋ
그리고 neighbor와 list 사이에 언더바 써줘야 네이밍이 자연스럽겠죠?

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_neighbors.xml
밑에 constraint 값 padding이 피그마랑 달라용... 리사이클러뷰 속 아이템과 전체 레이아웃 간의 패딩 꼭 계산해서 값 넣어주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectneighbor.xml
>              android:id="@+id/rv_gift_sendneighbor"
```suggestion
            android:id="@+id/rv_gift_send_neighbor"
```
사이에 언더바 넣기!!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectbouquet.xml
> +                android:text="워녕"
바뀌는 값이 들어가는 텍스트에는 tools:text 사용할 것

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_selectbouquet.xml
> +        android:id="@+id/linearLayout2"
이런식으로 네이밍 하면 안돼요!! 명확하게 해주기 ㅠㅠ linear보다는 constraint 사용합시다...

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/profile/ProfileFragment.kt
> +            startActivity(intent)
```suggestion
            startActivity( Intent(requireContext(), NeighborsActivity::class.java))
```
이런 식으로 코드 짤 수 있습니다!! 불필요한 변수 생성 지양하기!! 저두 나중에 이렇게 리팩할 예정입니다

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/profile/NeighborViewHolder.kt
> +        }
with(binding)으로 묶어주기

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/profile/NeighborDialogFragment.kt
> +        binding.tvNeighborNicknameInfo.text = neighborInfo.profileName
여기도 with(binding)으로 묶어주기

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/send/SelectneighborViewHolder.kt
> +        }
with(binding)여기두!!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/send/SelectneighborActivity.kt
SelectNeighborActivity로 네이밍 수정해주세요

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/send/SelectneighborActivity.kt
> +                startActivity(intent)
```suggestion
                Intent(this@SelectneighborActivity,SelectBouquetActivity::class.java).apply {
    putExtra("selectedNeighbor", neighbor)
    startActivity(this)
}
```
이제 스코프 함수 적용해봅시다!!

2024-07-15 15:51 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/send/SelectBouquetActivity.kt
> +        val neighborInfo = intent.getSerializableExtra("selectedNeighbor") as? NeighborInfo
"selectedNeighbor"는 companion object로 따로 상수화해주는게 좋습니다
const val NEIGHBOR_KEY = "selectedNeighbor" 
이렇게!!

2024-07-17 15:32 UTC, sehee0207 commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +            android:layout_height="52dp"
아하 우와 ... !!! 신기하네용!

2024-07-17 15:34 UTC, sehee0207 commented on app/src/main/res/layout/fragment_followcancel_dialog.xml
> +        android:layout_marginTop="40dp"
근데 피그마에서 요소랑 요소 사이의 정확한 마진 값이 몇 인지는 어떻게 확인할 수 있는건가요?? 늘 궁금했습니다 ..

2024-07-17 15:40 UTC, sehee0207 commented on app/src/main/res/layout/item_profile_neighborlist.xml
> +        android:text="선재"
오오 신기하네용

2024-07-17 15:40 UTC, sehee0207 commented on gradle/libs.versions.toml
> +agp = "8.4.0"
모르겠습니다 ... 제가 이런걸 바꿧나요??? ....  바꿧네요 ...

2024-07-17 16:23 UTC, sehee0207 commented on app/src/main/res/layout/activity_neighbors.xml
> +                android:id="@+id/rv_neighborslist"
글쿤요 ...

2024-07-17 16:28 UTC, sehee0207 commented on app/src/main/res/layout/activity_neighbors.xml
제가 계산하면 되는군요 알겟슴ㅂ니다!!!

2024-07-21 14:39 UTC, gaeulzzang approved these changes
![image](https://github.com/user-attachments/assets/b46163f8-780a-4646-a2eb-b1dd67f1786e)
이 코리만 반영하면 바로 어푸해줄게영~ 너무 잘한다!!!!

2024-07-21 14:39 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/send/SelectBouquetActivity.kt
> +        val NEIGHBOR_KEY = "selectedNeighbor"
상수는 하단에 이렇게 작성해주시는겁니다!!
```suggestion
        companion object {
            const val NEIGHBOR_KEY = "selectedNeighbor"
        }
```

2024-07-21 14:39 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_search_neighbor.xml
> +                android:id="@+id/text_search_neighbor_nouser"
네이밍 tv_로 수정

2024-07-21 14:39 UTC, gaeulzzang commented on app/src/main/res/layout/activity_gift_select_bouquet.xml
> +            app:srcCompat="@drawable/ic_add" />
android src를 사용하지 않고 app:srcCompat을 사용한 이유는 뭔가요?

2024-07-21 14:39 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/GiftFragment.kt
>              startActivity(intent)
```suggestion
            Intent(requireContext(), SearchNeighborActivity::class.java).apply {
                startActivity(this)
            }
```
이런식으로 코드 작성하면 불필요한 변수 생성을 막을 수 있습니다

2024-07-21 14:39 UTC, gaeulzzang commented on app/src/main/java/com/solux/flory/presentation/gift/GiftFragment.kt
>              startActivity(intent)
여기두!!

2024-07-21 15:39 UTC, merged